server:
  port: 18083
  servlet:
    session:
      timeout: 60
spring:
  datasource:
    url: jdbc:mysql://121.4.172.43:3306/petapp?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
#  mapper-locations: classpath*:io/parcelx/**/mapper/xml/**.xml
#  type-aliases-package: io.parcelx
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

